/**
 * 🎯 CONFIGURATION CENTRALISÉE DU SALON
 *
 * ⚠️ SOURCE DE VÉRITÉ UNIQUE
 * Ce fichier contient UNIQUEMENT de la configuration statique.
 *
 * ❌ AUCUNE donnée métier (services, catégories, prestations…)
 * ✅ Tout ce qui change rarement et permet de cloner le site
 */

export const salonConfig = {
  /* ----------------------------------------
   🏢 IDENTITÉ DU SALON
  ---------------------------------------- */
  identity: {
    name: "Salon Patricia Osores",
    shortName: "Salon Patricia Osores",
    ownerName: "Patricia Osores",
    city: "Liège",
    country: "Belgique",
    countryCode: "BE",
    tagline: "Coiffure personnalisée et créative",
    description:
      "Salon de coiffure Patricia Osores à Liège. Vous y trouverez un service personnalisé dans une ambiance chaleureuse et accueillante. Patricia met son savoir-faire au service de votre beauté.",
    longDescription:
      "Le salon de Patricia Osores à Liège vous propose une expérience unique de coiffure, dans une ambiance qui reflète l'harmonie et le soin du détail.",
  },


  /* ----------------------------------------
   📍 CONTACT & LOCALISATION
  ---------------------------------------- */
  contact: {
    email: "paty10j@hotmail.com",
    phone: "+32 496 71 41 15",
    phoneDisplay: "+32 496 71 41 15",
    phoneLink: "+32496714115",
    address: {
      street: "Place République Française 34",
      city: "Liège",
      postalCode: "",
      region: "Liège",
      country: "Belgique",
      countryCode: "BE",
      full: "Place République Française 34, Liège, Belgique",
    },
    coordinates: {
      latitude: 50.645,
      longitude: 5.573,
    },
    social: {
      instagram: "https://www.instagram.com/salon.de.coiffure.po/", 
      facebook: "https://www.facebook.com/p/Salon-de-coiffure-Patricia-Osores-100083957112347/",  
    },
  },


  /* ----------------------------------------
   🎨 THÈME VISUEL
  ---------------------------------------- */
  theme: {
    colors: { primary: "#BFA14A", dark: "#1A1A1A", light: "#F7F2EB", accent: "#3F3F3F", },

    images: {
      logo: "/images/logo.png",
      hero: "/images/landing1.jpg",
      ogImage: "/images/og-demo.jpg",
    },
  },

  /* ----------------------------------------
   🌐 SEO
  ---------------------------------------- */
  seo: {
    siteUrl: "https://salon-patricia-osores.be",
    siteUrlDev: "http://localhost:3000",
    title: "Salon Patricia Osores — Coiffure à Liège",
    titleShort: "Salon Patricia",
    description:
      "Le Salon Patricia Osores vous propose des coupes et des services de coiffure personnalisés à Liège.",
    keywords: [
      "coiffure Liège",
      "salon de coiffure Liège",
      "coiffure Patricia",
      "salon coiffure",
    ],
    lang: "fr",
    region: "BE",
  },


  /* ----------------------------------------
   ⭐ GOOGLE
  ---------------------------------------- */
  google: {
    businessUrl: "https://share.google/ccVClhR5sOl4jNFos",
    reviewUrl: "",
  },

  /* ----------------------------------------
   👤 ADMIN
  ---------------------------------------- */
  admin: {
    email: "contact@jeremy-caron-labalette.fr",
    name: "Patricia",
    fullName: "Patricia Osores",
    salon: "Salon Patricia Osores",
    locale: "be",
  },

  /* ----------------------------------------
   📧 EMAILS
  ---------------------------------------- */
  emails: {
    from: "contact@salon-patricia-osores.be",
    fromName: "Salon Patricia Osores",
    replyTo: "paty10j@hotmail.com",

    subjects: {
      newBooking: "[Salon Patricia] Nouvelle demande de rendez-vous — {{clientName}}",
      clientConfirmation: "[Salon Patricia] Confirmation de rendez-vous",
      bookingAccepted: "[Salon Patricia] Votre rendez-vous est confirmé",
      bookingRejected: "[Salon Patricia] Votre rendez-vous a été modifié",
      reviewRequest: "[Salon Patricia] Votre avis est important",
    },

    reviewRequestDelayHours: 2,
    cronHour: 20,
  },


  /* ----------------------------------------
   📅 HORAIRES
  ---------------------------------------- */
  schedule: {
    timezone: "Europe/Brussels",

    weekly: {
      monday: { open: "09:00", close: "18:00", closed: false },
      tuesday: { open: "09:00", close: "18:00", closed: false },
      wednesday: { open: "09:00", close: "18:00", closed: false },
      thursday: { open: "09:00", close: "18:00", closed: false },
      friday: { open: "09:00", close: "18:00", closed: false },
      saturday: { open: "09:00", close: "17:00", closed: false },
      sunday: { open: "", close: "", closed: true },
    },

    slotInterval: 30,
    bookingDaysAhead: 7,
    autoGenerateDays: 30,
  },

  /* ----------------------------------------
   ⚖️ LÉGAL
  ---------------------------------------- */
  // legal: {
  //   vatNumber: "FR0000000000",
  //   businessType: "Site de démonstration",
  //   foundedYear: 2024,
  // },

  /* ----------------------------------------
   🌍 LOCALISATION
  ---------------------------------------- */
  localization: {
    defaultLocale: "be",
    supportedLocales: ["be"],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "dd/MM/yyyy",
    timeFormat: "HH:mm",
  },

  /* ----------------------------------------
   ⚙️ FEATURES
  ---------------------------------------- */
  features: {
    googleCalendarSync: true,
    automaticReviews: true,
    blog: false,
    testimonials: true,
    gallery: true,
    contactForm: true,
    maxGalleryImages: 12,

    // 🔑 règle métier globale autorisée
    maxFeaturedServices: 3,
  },

  /* ----------------------------------------
   📊 TECHNIQUE
  ---------------------------------------- */
  technical: {
    itemsPerPage: 20,
    sessionDuration: 3600,
    refreshTokenDuration: 604800,
    maxImageSize: 5,
    allowedImageFormats: ["jpg", "jpeg", "png", "webp"],
  },
} as const

/* ----------------------------------------
   🔧 TYPES
---------------------------------------- */
export type SalonConfig = typeof salonConfig
export type ThemeColors = typeof salonConfig.theme.colors
export type ContactInfo = typeof salonConfig.contact
export type SeoConfig = typeof salonConfig.seo
export type AdminConfig = typeof salonConfig.admin

/* ----------------------------------------
   🛠️ HELPERS
---------------------------------------- */
export const getSiteUrl = () =>
  process.env.NODE_ENV === "production"
    ? salonConfig.seo.siteUrl
    : salonConfig.seo.siteUrlDev

export const getFullAddress = () =>
  salonConfig.contact.address.full

export const getFullSalonName = () =>
  `${salonConfig.identity.name} - ${salonConfig.identity.city}`

export const getFromEmail = () =>
  `"${salonConfig.emails.fromName}" <${salonConfig.emails.from}>`

export const getFormattedSchedule = () => {
  const days = {
    monday: "Lundi",
    tuesday: "Mardi",
    wednesday: "Mercredi",
    thursday: "Jeudi",
    friday: "Vendredi",
    saturday: "Samedi",
    sunday: "Dimanche",
  }

  return Object.entries(salonConfig.schedule.weekly).map(
    ([key, value]) => ({
      jour: days[key as keyof typeof days],
      heures: value.closed
        ? "Fermé"
        : `${value.open} - ${value.close}`,
    })
  )
}

export default salonConfig
