/**
 * 🎯 CONFIGURATION CENTRALISÉE DU SALON
 *
 * ⚠️ SOURCE DE VÉRITÉ UNIQUE
 * Ce fichier contient UNIQUEMENT de la configuration statique.
 *
 * ❌ AUCUNE donnée métier (services, catégories, prestations…)
 * ✅ Tout ce qui change rarement et permet de cloner le site
 */

export const salonConfig = {
  /* ----------------------------------------
   🏢 IDENTITÉ DU SALON
  ---------------------------------------- */
  identity: {
    name: "Salon Démo",
    shortName: "Salon Démo",
    ownerName: "Jeremy Caron",
    city: "Chantilly",
    country: "France",
    countryCode: "FR",
    tagline: "Salon de démo — Coiffure",
    description:
      "Salon Démo est un site de démonstration présentant une solution moderne de prise de rendez-vous pour salons de coiffure et d’esthétique.",
    longDescription:
      "Ce salon de démonstration a été conçu pour illustrer l’ensemble des fonctionnalités d’un site professionnel de réservation en ligne, pensé pour les salons de services.",
  },

  /* ----------------------------------------
   📍 CONTACT & LOCALISATION
  ---------------------------------------- */
  contact: {
    email: "contact@jeremy-caron-labalette.fr",
    phone: "+33 6 19 51 50 86",
    phoneDisplay: "+33 6 19 51 50 86",
    phoneLink: "+33619515086",

    address: {
      street: "Centre-ville",
      city: "Chantilly",
      postalCode: "60500",
      region: "Oise",
      country: "France",
      countryCode: "FR",
      full: "Chantilly, 60500, Oise, France",
    },

    coordinates: {
      latitude: 49.1946,
      longitude: 2.4712,
    },

    social: {
      instagram: "",
      facebook: "",
    },
  },

  /* ----------------------------------------
   🎨 THÈME VISUEL
  ---------------------------------------- */
  theme: {
    colors: { primary: "#BFA14A", dark: "#1A1A1A", light: "#F7F2EB", accent: "#3F3F3F", },

    images: {
      logo: "/images/logo.png",
      hero: "/images/landing.jpg",
      ogImage: "/images/og-demo.jpg",
    },
  },

  /* ----------------------------------------
   🌐 SEO
  ---------------------------------------- */
  seo: {
    siteUrl: "https://demo.jeremy-caron-labalette.fr",
    siteUrlDev: "http://localhost:3000",
    title: "Salon Démo — Prise de rendez-vous en ligne",
    titleShort: "Salon Démo",
    description:
      "Site de démonstration d’un salon avec prise de rendez-vous en ligne, conçu par Jeremy Caron.",
    keywords: [
      "site salon de coiffure",
      "prise de rendez-vous en ligne",
      "site de démonstration",
      "réservation salon",
    ],
    lang: "fr",
    region: "FR",
  },

  /* ----------------------------------------
   ⭐ GOOGLE
  ---------------------------------------- */
  google: {
    businessUrl: "",
    reviewUrl: "",
  },

  /* ----------------------------------------
   👤 ADMIN
  ---------------------------------------- */
  admin: {
    email: "contact@jeremy-caron-labalette.fr",
    name: "Jeremy",
    fullName: "Jeremy Caron",
    salon: "Salon Démo",
    locale: "fr",
  },

  /* ----------------------------------------
   📧 EMAILS
  ---------------------------------------- */
  emails: {
    from: "contact@jeremy-caron-labalette.fr",
    fromName: "Salon Démo",
    replyTo: "contact@jeremy-caron-labalette.fr",

    subjects: {
      newBooking: "[DEMO] Nouvelle demande de rendez-vous — {{clientName}}",
      clientConfirmation:
        "[DEMO] Demande de rendez-vous reçue",
      bookingAccepted: "[DEMO] Votre rendez-vous est confirmé",
      bookingRejected: "[DEMO] Modification de votre rendez-vous",
      reviewRequest: "[DEMO] Votre avis compte pour nous",
    },

    reviewRequestDelayHours: 2,
    cronHour: 20,
  },

  /* ----------------------------------------
   📅 HORAIRES
  ---------------------------------------- */
  schedule: {
    timezone: "Europe/Paris",

    weekly: {
      monday: { open: "09:00", close: "18:00", closed: false },
      tuesday: { open: "09:00", close: "18:00", closed: false },
      wednesday: { open: "09:00", close: "18:00", closed: false },
      thursday: { open: "09:00", close: "18:00", closed: false },
      friday: { open: "09:00", close: "18:00", closed: false },
      saturday: { open: "09:00", close: "17:00", closed: false },
      sunday: { open: "", close: "", closed: true },
    },

    slotInterval: 30,
    bookingDaysAhead: 7,
    autoGenerateDays: 30,
  },

  /* ----------------------------------------
   ⚖️ LÉGAL
  ---------------------------------------- */
  legal: {
    vatNumber: "FR0000000000",
    businessType: "Site de démonstration",
    foundedYear: 2024,
  },

  /* ----------------------------------------
   🌍 LOCALISATION
  ---------------------------------------- */
  localization: {
    defaultLocale: "fr",
    supportedLocales: ["fr"],
    currency: "EUR",
    currencySymbol: "€",
    dateFormat: "dd/MM/yyyy",
    timeFormat: "HH:mm",
  },

  /* ----------------------------------------
   ⚙️ FEATURES
  ---------------------------------------- */
  features: {
    googleCalendarSync: true,
    automaticReviews: true,
    blog: false,
    testimonials: true,
    gallery: true,
    contactForm: true,
    maxGalleryImages: 12,

    // 🔑 règle métier globale autorisée
    maxFeaturedServices: 3,
  },

  /* ----------------------------------------
   📊 TECHNIQUE
  ---------------------------------------- */
  technical: {
    itemsPerPage: 20,
    sessionDuration: 3600,
    refreshTokenDuration: 604800,
    maxImageSize: 5,
    allowedImageFormats: ["jpg", "jpeg", "png", "webp"],
  },
} as const

/* ----------------------------------------
   🔧 TYPES
---------------------------------------- */
export type SalonConfig = typeof salonConfig
export type ThemeColors = typeof salonConfig.theme.colors
export type ContactInfo = typeof salonConfig.contact
export type SeoConfig = typeof salonConfig.seo
export type AdminConfig = typeof salonConfig.admin

/* ----------------------------------------
   🛠️ HELPERS
---------------------------------------- */
export const getSiteUrl = () =>
  process.env.NODE_ENV === "production"
    ? salonConfig.seo.siteUrl
    : salonConfig.seo.siteUrlDev

export const getFullAddress = () =>
  salonConfig.contact.address.full

export const getFullSalonName = () =>
  `${salonConfig.identity.name} - ${salonConfig.identity.city}`

export const getFromEmail = () =>
  `"${salonConfig.emails.fromName}" <${salonConfig.emails.from}>`

export const getFormattedSchedule = () => {
  const days = {
    monday: "Lundi",
    tuesday: "Mardi",
    wednesday: "Mercredi",
    thursday: "Jeudi",
    friday: "Vendredi",
    saturday: "Samedi",
    sunday: "Dimanche",
  }

  return Object.entries(salonConfig.schedule.weekly).map(
    ([key, value]) => ({
      jour: days[key as keyof typeof days],
      heures: value.closed
        ? "Fermé"
        : `${value.open} - ${value.close}`,
    })
  )
}

export default salonConfig
